apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-ds
  namespace: grafana
spec:
  # This must match the labels on your Grafana CR (you used dashboards: "grafana")
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    uid: prometheus
    name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-frontend.prometheus.svc:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
      httpMethod: POST
