apiVersion: v1
kind: Service
metadata:
  name: currencyservice-metrics
  namespace: my-app
  labels:
    app: myapp
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9464"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: currencyservice
  ports:
    - name: metrics
      port: 9464
      targetPort: 9464
  type: ClusterIP


---

apiVersion: v1
kind: Service
metadata:
  name: payment-metrics
  namespace: my-app
  labels:
    app: myapp
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9464"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: paymentservice
  ports:
    - name: metrics
      port: 9464
      targetPort: 9464
  type: ClusterIP